feat: Tag new release

diff --git a/springwolf-ui/.github/workflows/publish-release.yml b/springwolf-ui/.github/workflows/publish-release.yml
--- a/springwolf-ui/.github/workflows/publish-release.yml
+++ b/springwolf-ui/.github/workflows/publish-release.yml
@@ -3,6 +3,7 @@ name: Publish release
 on: workflow_dispatch
 
 permissions:
+  contents: write
   packages: write
 
 jobs:
@@ -11,14 +12,15 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Set up JDK 1.8
-        uses: actions/setup-java@v1
+      - name: Set up JDK
+        uses: actions/setup-java@v3
         with:
-          java-version: 1.8
+          distribution: 'temurin'
+          java-version: '17'
 
       - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
-        
+
       - name: Publish package
         run: ./gradlew publish
         env:
@@ -27,3 +29,14 @@ jobs:
           ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD}}
           ORG_GRADLE_PROJECT_MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
           ORG_GRADLE_PROJECT_MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
+
+      - name: Tag version
+        run: |
+          VERSION=$(./gradlew properties | grep "version:" | awk '{print $2}')
+          TAG="v$VERSION"
+          git tag "$TAG"
+
+          echo "Publishing tag"
+          git push origin "$TAG" || true # Do not fail, if the tag already exists
+        env:
+          ORG_GRADLE_PROJECT_SNAPSHOT: false
