chore: Update springwolf-ui project references

diff --git a/.github/workflows/publish-releases.yml b/.github/workflows/publish-releases.yml
--- a/.github/workflows/publish-releases.yml
+++ b/.github/workflows/publish-releases.yml
@@ -142,3 +142,37 @@ jobs:
           git push origin "$TAG" || true # Do not fail, if the tag already exists
         env:
           ORG_GRADLE_PROJECT_SNAPSHOT: false
+
+  publish-springwolf-ui-release:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Set up JDK
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v2
+
+      - name: Publish
+        run: ./gradlew -p springwolf-ui publish
+        env:
+          ORG_GRADLE_PROJECT_SNAPSHOT: false
+          ORG_GRADLE_PROJECT_SIGNINGKEY: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGKEY}}
+          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD}}
+          ORG_GRADLE_PROJECT_MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
+          ORG_GRADLE_PROJECT_MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
+
+      - name: Tag version
+        run: |
+          VERSION=$(./gradlew -p springwolf-ui properties | grep "version:" | awk '{print $2}')
+          TAG="springwolf-ui-$VERSION"
+          git tag "$TAG"
+
+          echo "Publishing tag"
+          git push origin "$TAG" || true # Do not fail, if the tag already exists
+        env:
+          ORG_GRADLE_PROJECT_SNAPSHOT: false
